apiVersion: v1
kind: Service
metadata:
  name: ingweb
spec:
  selector:
    app: ingweb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingweb
  labels:
    app: ingweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingweb
  template:
    metadata:
      labels:
        app: ingweb
    spec:
      containers:
      - name: ingweb
        image: hayk99/git-race
        ports:
        - containerPort: 8080